// components/modals/ExplanationModal.jsx
'use client';
import { useApp } from '../../context/AppContext';
import ModalSlot from '../ModalSlot';

export default function ExplanationModal() {
  const { modal } = useApp();
  const transObj = { muyassar: 'الميسر', jalalayn: 'الجلالين' };
  const text = modal.data?.text || '';
  const explainer = transObj[modal.data?.explainer] || '';

  return (
    <ModalSlot name="explanation">
      <div className="pl-[10px]">
        <h3 className="modal-heading m-0 border-b-2 border-[#6a11cb] inline-block pb-[5px] mb-[20px] text-[#333]">
          تفسير {explainer}
        </h3>
        <p className="modal-text text-[#666] m-0 leading-[25px]">{text}</p>
      </div>
    </ModalSlot>
  );
}

// src/modals/ExplanationModal.vue
<template>
  <ModalSlot name="explanation">
    <div class="explanationInnerWrapper">
      <h3>تفسير {{ explainer }}</h3>
      <p>{{ text }}</p>
    </div>
  </ModalSlot>
</template>

<script>
  import ModalSlot from "../components/modalSlot.vue";

  export default {
    components: { ModalSlot },

    data() {
      return {
        text: "",
        explainer: "",
      };
    },
    mounted() {
      console.log("mounted explanation");
      const transObj = {
        muyassar: "الميسر",
        jalalayn: "الجلالين",
      };
      if (this.$parent.modal.name === "explanation") {
        this.text = this.$parent.modal.data.text;
        this.explainer = this.$parent.modal.data.explainer;
        this.explainer = transObj[this.explainer];
      }
    },
    methods: {},
  };
</script>

<style lang="scss">
  .explanationInnerWrapper {
    h3 {
      margin: 0;
      border-bottom: 2px solid #6a11cb;
      display: inline-block;
      padding-bottom: 5px;
      margin-bottom: 20px;
      color: #333;
    }
    p {
      color: #666;
      margin: 0;
      line-height: 25px;
    }
  }
</style>
