// components/modals/BookmarksModal.jsx
'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useApp } from '../../context/AppContext';
import ModalSlot from '../ModalSlot';
import icons from '../../services/icons';
import { juz, arNum } from '../../services/filters';

export default function BookmarksModal() {
  const router = useRouter();
  const { setModal, readViewEnabled, setCurrentVerse, setHighlightCurrentVerse, readViewRef } = useApp();
  const [hide, setHide] = useState(false);
  const [tab, setTab] = useState('verse');
  const [tabs] = useState([
    { text: 'أية', tab: 'verse', checked: true },
    { text: 'صفحة', tab: 'page', checked: true },
  ]);
  const [bookmarks, setBookmarks] = useState(
    () => JSON.parse(localStorage.getItem('bookmarks')) || []
  );
  const [highlightedVerses, setHighlightedVerses] = useState(
    () => JSON.parse(localStorage.getItem('highlightedVerses')) || []
  );

  const removeVerse = (obj) => {
    window.oConfirm({
      title: 'المفضلة',
      desc: 'هل تريد حذف هذه الأية؟',
      btns: { cancel: { exists: true, text: 'الغاء' }, okay: { text: 'نعم' } },
    }).then(res => {
      if (res) {
        const updated = highlightedVerses.filter(item => item.globalVerse !== obj.globalVerse);
        setHighlightedVerses(updated);
        localStorage.setItem('highlightedVerses', JSON.stringify(updated));
      }
    });
  };

  const removePage = (obj) => {
    window.oConfirm({
      title: 'المفضلة',
      desc: 'هل تريد حذف هذه الصفحة؟',
      btns: { cancel: { exists: true, text: 'الغاء' }, okay: { text: 'نعم' } },
    }).then(res => {
      if (res) {
        const updated = bookmarks.filter(item => item.page !== obj.page);
        setBookmarks(updated);
        localStorage.setItem('bookmarks', JSON.stringify(updated));
      }
    });
  };

  const navigateTo = (page, globalVerse = null) => {
    setHide(true);
    if (globalVerse !== null) {
      setCurrentVerse(globalVerse);
      setHighlightCurrentVerse(true);
    } else {
      setCurrentVerse(null);
      setHighlightCurrentVerse(null);
    }
    if (readViewEnabled && readViewRef.current) {
      readViewRef.current.setPage(+page);
    } else {
      router.push('/read/' + page);
    }
  };

  const goTo = (e) => {
    if (e.target.nodeName !== 'LI') return;
    const verseAttr = e.target.getAttribute('data-verse');
    const pageAttr = e.target.getAttribute('data-page');
    if (verseAttr) {
      const [page, globalVerse] = verseAttr.split('-');
      navigateTo(page, globalVerse);
    } else if (pageAttr) {
      navigateTo(pageAttr);
    }
  };

  return (
    <ModalSlot name="bookmark" hide={hide}>
      <div className="bookmark-inner w-full min-h-[70px] mt-[5px] rounded-[3px] border border-[#d8d8d8]">
        <nav className="bookmark-nav px-[10px] pl-[35px] pb-[5px] pt-[10px] border-b border-[#d8d8d8] relative bg-white">
          <ul className="m-0 p-0 pb-[5px] pl-[5px] list-none flex whitespace-nowrap overflow-auto scrollbar">
            {tabs.map((item, index) => item.tab && (
              <li
                key={index}
                className={[
                  'hidden cursor-pointer px-[10px] pt-[5px] pb-[2.5px] rounded-[50px] ml-[10px] border border-[#eee] select-none last:ml-0',
                  item.tab === tab ? 'bg-[#2f70ec] border-[#2f70ec] [&>a]:text-white [&>a]:font-bold' : '',
                  item.checked ? '!inline-block' : '',
                ].join(' ')}
                onClick={() => setTab(item.tab)}
              >
                <a className="pointer-events-none no-underline text-center block text-[14px] text-[#666] font-tajawal">
                  {item.text}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        <div>
          <ul className="m-0 p-[10px] list-none overflow-auto h-[calc(100vh-170px)] scrollbar" onClick={goTo}>
            {tab === 'verse' && (
              <>
                {highlightedVerses.map((item, index) => (
                  <li
                    key={index}
                    className="result-item border-b border-[#eee] py-[10px] rounded-[3px] cursor-pointer overflow-hidden first:pt-0 last:border-0 last:pb-0 hover:[&>a]:text-[#647eff]"
                    data-verse={`${item.page}-${item.globalVerse}`}
                  >
                    <div className="verseInfo pointer-events-none overflow-hidden select-none">
                      <span className="verseInfo__name select-none text-xs font-bold text-[#666] font-kitab float-left">{item.name}</span>
                      <span className="verseInfo__juz select-none text-xs font-bold text-[#666] font-kitab float-right ml-[5px]">{juz(item.juz)}</span>
                      <span className="verseInfo__separator select-none text-xs font-bold text-[#666] font-kitab float-right ml-[5px]">-</span>
                      <span className="verseInfo__page select-none text-xs font-bold text-[#666] font-kitab float-right ml-[5px]">صفحة {arNum(item.page)}</span>
                    </div>
                    <a className="block font-kitab text-[20px] font-bold text-[#666] no-underline px-[5px] py-[10px] rounded-[3px] transition-[background_0.1s_ease] select-none pointer-events-none">
                      {item.text}
                      <span className="pointer-events-none font-[Arial,sans-serif] w-[35px] h-[35px] leading-[35px] rounded-full inline-block text-[14px] text-center mx-[8px] select-none bg-[#5fd068] text-white shadow-[0_0_3px_1px_rgba(0,0,0,0.15)]">
                        {arNum(item.localVerse)}
                      </span>
                      <button
                        className="o-btn w-[35px] h-[35px] p-0 rounded-full relative top-[11px] border-transparent bg-[#f94c66] m-0 pointer-events-auto"
                        onClick={(e) => { e.stopPropagation(); removeVerse(item); }}
                        dangerouslySetInnerHTML={{ __html: icons.close }}
                      />
                    </a>
                  </li>
                ))}
                {!highlightedVerses.length && (
                  <div className="empty-msg text-center my-[10px] text-[#666] select-none">لايوجد أيات محفوظة</div>
                )}
              </>
            )}
            {tab === 'page' && (
              <>
                {bookmarks.map((item, index) => (
                  <li
                    key={index}
                    className="result-item border-b border-[#eee] py-[10px] rounded-[3px] cursor-pointer overflow-hidden first:pt-0 last:border-0 last:pb-0"
                    data-page={item.page}
                  >
                    <div className="pointer-events-none float-right select-none">
                      <span className="surahInfo__page select-none font-bold text-[#666] font-[Arial,sans-serif] text-[14px] ml-[10px] w-[35px] h-[35px] p-0 rounded-full relative border-transparent bg-[#2f70ec] float-right text-center text-white leading-[38px]">
                        {arNum(item.page)}
                      </span>
                      <span className="surahInfo__name select-none font-bold text-[#666] font-kitab text-[20px]">
                        سُورَةُ {item.name}
                      </span>
                    </div>
                    <button
                      className="o-btn w-[35px] h-[35px] p-0 rounded-full border-transparent bg-[#f94c66] float-left m-[2px] relative"
                      onClick={(e) => { e.stopPropagation(); removePage(item); }}
                      dangerouslySetInnerHTML={{ __html: icons.close }}
                    />
                  </li>
                ))}
                {!bookmarks.length && (
                  <div className="empty-msg text-center my-[10px] text-[#666] select-none">لايوجد صفحات محفوظة</div>
                )}
              </>
            )}
          </ul>
        </div>
      </div>
    </ModalSlot>
  );
}

// vueApp/src/modals/BookmarksModal.vue
<template>
  <ModalSlot name="bookmark" :hide="hide">
    <div class="bookmarkInnerWrapper">
      <!-- menu -->
      <nav>
        <ul class="scrollbar">
          <template v-for="(item, index) in tabs" :key="index">
            <li v-if="item.tab" :class="{ active: item.tab === tab, checked: item.checked }" @click="handleSelectedTabs(item)">
              <a>{{ item.text }}</a>
            </li>
          </template>
        </ul>
      </nav>

      <!-- resutls -->
      <div class="results">
        <ul @click="goTo($event)" class="scrollbar">
          <template v-if="tab === 'verse'">
            <li v-for="(item, index) of highlightedVerses" :key="index" :data-verse="item.page + '-' + item.globalVerse">
              <div class="verseInfo">
                <span class="verseInfo__name">{{ item.name }}</span>
                <span class="verseInfo__juz">{{ $filters.juz(item.juz) }}</span>
                <span class="verseInfo__separator">-</span>
                <span class="verseInfo__page" v-arNum>صفحة {{ item.page }}</span>
              </div>
              <a>
                {{ item.text }}
                <span class="verseNum" v-arNum>{{ item.localVerse }}</span>
                <button class="o-btn remove" @click="removeVerse(item)" v-html="closeIcon"></button>
              </a>
            </li>
            <div class="emptyBookmarks" v-if="!highlightedVerses.length">لايوجد أيات محفوظة</div>
          </template>

          <template v-else-if="tab === 'page'">
            <li v-for="(item, index) of bookmarks" :key="index" :data-page="item.page">
              <div class="surahInfo">
                <span class="surahInfo__page" v-arNum>{{ item.page }}</span>
                <span class="surahInfo__name">سُورَةُ {{ item.name }}</span>
              </div>
              <button class="o-btn remove" @click="removePage(item)" v-html="closeIcon"></button>
            </li>
            <div class="emptyBookmarks" v-if="!bookmarks.length">لايوجد صفحات محفوظة</div>
          </template>
        </ul>
      </div>
    </div>
  </ModalSlot>
</template>

<script>
  import ModalSlot from "../components/modalSlot.vue";
  import icons from "../services/icons";
  export default {
    components: { ModalSlot },
    data() {
      return {
        hide: false,
        tabs: [
          { text: "أية", tab: "verse", checked: true },
          { text: "صفحة", tab: "page", checked: true },
        ],
        tab: "verse",
        bookmarks: [],
        highlightedVerses: [],
        closeIcon: icons.close,
      };
    },
    beforeMount() {
      this.bookmarks = JSON.parse(localStorage.getItem("bookmarks")) || [];
      this.highlightedVerses = JSON.parse(localStorage.getItem("highlightedVerses")) || [];
    },
    mounted() {
      this.hide = false;
    },
    unmounted() {
      this.hide = false;
    },
    methods: {
      removeVerse(obj) {
        oConfirm({
          title: "المفضلة",
          desc: "هل تريد حذف هذه الأية؟",
          btns: { cancel: { exists: true, text: "الغاء" }, okay: { text: "نعم" } },
        }).then(res => {
          if (res) {
            this.highlightedVerses = this.highlightedVerses.filter(item => item.globalVerse !== obj.globalVerse);
            localStorage.setItem("highlightedVerses", JSON.stringify(this.highlightedVerses));
          }
        });
      },
      removePage(obj) {
        oConfirm({
          title: "المفضلة",
          desc: "هل تريد حذف هذه الصفحة؟",
          btns: { cancel: { exists: true, text: "الغاء" }, okay: { text: "نعم" } },
        }).then(res => {
          if (res) {
            this.bookmarks = this.bookmarks.filter(item => item.page !== obj.page);
            localStorage.setItem("bookmarks", JSON.stringify(this.bookmarks));
          }
        });
      },
      handleSelectedTabs(item) {
        this.tab = item.tab;
      },
      goTo(e) {
        if (e.target.nodeName === "LI") {
          const hasAttr = attr => e.target.getAttribute(attr);
          if (hasAttr("data-verse")) {
            const [page, globalVerse] = hasAttr("data-verse").split("-");
            console.log({ page, globalVerse });
            this.hide = true; // hide modal
            this.$parent.currentVerse = globalVerse;
            this.$parent.highlightCurrentVerse = true;
            if (this.$parent.readViewEnabled) {
              if (readViewComp) readViewComp.setPage(page);
              else console.warn("readViewComp is NOT defined");
            } else {
              this.$router.push("/read/" + page);
            }
          } else if (hasAttr("data-page")) {
            const page = hasAttr("data-page");
            console.log({ page });
            this.hide = true; // hide modal
            this.$parent.currentVerse = null;
            this.$parent.highlightCurrentVerse = null;
            if (this.$parent.readViewEnabled) {
              if (readViewComp) readViewComp.setPage(page);
              else console.warn("readViewComp is NOT defined");
            } else {
              this.$router.push("/read/" + page);
            }
          }
        }
      },
    },
  };
</script>

<style lang="scss">
  .bookmarkInnerWrapper {
    width: 100%;
    min-height: 70px;
    margin-top: 5px;
    border-radius: 3px;
    border: 1px solid #d8d8d8;

    nav {
      padding: 10px;
      padding-left: 35px;
      padding-bottom: 5px;
      border-bottom: 1px solid #d8d8d8;
      position: relative;
      background: white;

      ul {
        margin: 0;
        padding: 0;
        padding-bottom: 5px;
        padding-left: 5px;
        list-style-type: none;
        display: flex;
        white-space: nowrap;
        overflow: auto;
        li {
          display: none;
          cursor: pointer;
          padding: 5px 10px 2.5px 10px;
          border-radius: 50px;
          margin-left: 10px;
          border: 1px solid #eee;
          user-select: none;
          &:last-of-type {
            margin-left: 0;
          }
          a {
            pointer-events: none;
            text-decoration: none;
            text-align: center;
            display: block;
            font-size: 14px;
            color: #666;
            font-family: "Tajawal", Helvetica, Arial, sans-serif;
          }
          &.active {
            background: #2f70ec;
            border-color: #2f70ec;
            a {
              color: white;
              font-weight: bold;
            }
          }
          &.checked {
            display: inline-block;
          }
        }
      }
    }
    .results {
      ul {
        margin: 0;
        padding: 10px;
        list-style-type: none;
        overflow: auto;
        height: calc(100vh - 170px);
        .emptyBookmarks {
          text-align: center;
          margin: 10px 0;
          color: #666;
          user-select: none;
        }
        li {
          border-bottom: 1px solid #eee;
          padding: 10px 0;
          border-radius: 3px;
          cursor: pointer;
          overflow: hidden;

          a {
            display: block;
            font-family: "Kitab-Regular2";
            font-size: 20px;
            font-weight: bold;
            color: #666;
            text-decoration: none;
            padding: 10px 5px;
            border-radius: 3px;
            transition: background 0.1s ease;
            user-select: none;
            pointer-events: none;

            .verseNum {
              pointer-events: none;
              font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
              width: 35px;
              height: 35px;
              line-height: 35px;
              border-radius: 50%;
              display: inline-block;
              font-size: 14px;
              text-align: center;
              margin: 0 8px;
              user-select: none;
              background: #5fd068;
              color: white;
              box-shadow: 0 0 3px 1px rgba(0, 0, 0, 15%);
            }
          }

          &:first-of-type {
            padding-top: 0;
          }
          &:last-of-type {
            border: 0;
            padding-bottom: 0;
          }

          button.remove {
            width: 35px;
            height: 35px;
            pointer-events: auto;
            padding: 0;
            border-radius: 50%;
            position: relative;
            top: -4px;
            border-color: transparent;
            position: relative;
            background: #f94c66;
            svg {
              width: 20px;
              height: 20px;
              position: absolute;
              top: 50%;
              left: 50%;
              transform: translate(-50%, -50%);
              color: white;
            }
          }

          .verseInfo {
            pointer-events: none;
            overflow: hidden;
            user-select: none;
            span {
              user-select: none;
              font-size: 12px;
              font-weight: bold;
              color: #666;
              font-family: "Kitab-Regular2";
              float: left;
            }
            &__page,
            &__juz,
            &__separator {
              float: right !important;
              margin-left: 5px;
            }
            &__juz {
            }
            &__separator {
            }
          }

          .surahInfo {
            pointer-events: none;
            float: right;
            user-select: none;
            span {
              user-select: none;
              font-weight: bold;
              color: #666;
            }
            &__name {
              font-family: "Kitab-Regular2";
              font-size: 20px;
            }
            &__page {
              font-size: 14px;
              font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
              margin-left: 10px;
              width: 35px;
              height: 35px;
              padding: 0;
              border-radius: 50%;
              position: relative;
              border-color: transparent;
              background: #5fd068;
              float: right;
              text-align: center;
              color: white !important;
              line-height: 38px;
            }
            & ~ button.remove {
              top: auto;
              float: left;
            }
          }

          &:hover {
            a,
            .surahInfo__name {
              background: -webkit-linear-gradient(315deg, #42d392 25%, #647eff);
              background-clip: text;
              -webkit-background-clip: text;
              -webkit-text-fill-color: transparent;
              transition: background 0.1s ease;
              .verseNum {
                background: #5fd068 !important;
                color: white !important;
                box-shadow: 0 0 3px 1px rgba(0, 0, 0, 15%) !important;
                background-clip: initial !important;
                -webkit-background-clip: initial !important;
                -webkit-text-fill-color: white !important;
              }
            }
          }
        }
      }
    }
  }
</style>
