// vueApp/src/modals/OptionsRect.vue
<template>
  <div class="OptionsRect" :style="calcStyle">
    <div class="highlight" @click="highlight(options.obj, $event)">
      <button class="orange"></button>
      <button class="purple"></button>
      <button class="blue"></button>
      <button class="noColor"></button>
    </div>
    <div class="trans">
      <button @click="getVerseTrans(options.obj)" v-html="translateIcon"></button>
    </div>
    <div class="copyText">
      <button @click="copyText(options.obj)" v-html="clipboardIcon"></button>
    </div>
    <div class="explain">
      <button @click="getVerseExplanation(options.obj)" v-html="bookIcon"></button>
    </div>
    <div class="sound">
      <button @click="reciteVerse(options.obj)" v-html="playIcon"></button>
    </div>
  </div>
</template>

<script>
  import icons from "../services/icons";
  export default {
    computed: {
      calcStyle() {
        if (this.width && this.height) {
          const obj = { top: this.options.coords.top - this.height - 5 + "px" };
          if (this.options.coords.width < this.width) {
            obj.left = this.options.coords.right - this.width + "px";
          } else {
            obj.left = this.options.coords.left + "px";
          }
          return obj;
        }
      },
    },
    data() {
      return {
        translateIcon: icons.translate,
        clipboardIcon: icons.clipboard,
        bookIcon: icons.book,
        playIcon: icons.play,
        height: 0,
        width: 0,
      };
    },
    updated() {
      if (this.$parent.optionsRectShown && !this.$parent.isLoading) {
        this.width = this.$el.getBoundingClientRect().width;
        this.height = this.$el.getBoundingClientRect().height;
      }
    },
    mounted() {
      // blur
      this.$parent.$el.onclick = e => {
        if (e.target !== this.$el && e.target !== this.options.coords.elm) {
          this.$parent.optionsRectShown = false;
        }
      };
    },
    props: ["options", "audio", "shown"],
    methods: {
      reciteVerse(obj) {
        if (this.isOffline()) return this.showNetworkHint();
        if (verses) {
          obj = verses[obj.globalVerse - 1]; // get full obj data
          console.log(obj);

          // show the page of current working verse
          if (this.$parent.isAuto && this.$parent.pageNum !== obj.page && obj.page <= 604) this.$parent.setPage(obj.page);

          // start reset
          if (!this.audio.paused) {
            this.audio.pause();
            this.$emit("update", { isPlaying: false, isInitialPlaying: true });
          }
          this.audio.src = "";
          this.$parent.deselectVerses();
          // end reset

          let globalVerse = obj.globalVerse;
          const rate = 64;
          const url = "https://cdn.islamic.network/quran/audio/" + rate + "/ar." + this.options.reciter + "/" + globalVerse + ".mp3";
          this.audio.src = url;

          this.audio.onended = () => {
            console.log("ended");
            // reset
            this.$emit("update", { isPlaying: false, isInitialPlaying: true });
            this.$parent.deselectVerses();

            // auto reciting
            if (this.$parent.isAuto) {
              if (globalVerse < 6236) {
                this.reciteVerse({ globalVerse: (globalVerse += 1) });
              }
            }
          };

          this.audio.play();
          this.$emit("update", { isPlaying: true, isInitialPlaying: true });
          setTimeout(() => {
            const currentVerse = document.getElementById("verse_" + obj.globalVerse);
            console.log({ currentVerse });
            if (currentVerse) {
              currentVerse.scrollIntoView({ behavior: "smooth", block: "end", inline: "nearest" });
              currentVerse.classList.add("selected");
            }
          }, 1);
        } else {
          console.warn("verse variable is NOT defined");
        }
      },
      getVerseExplanation(obj) {
        if (this.isOffline()) return this.showNetworkHint();
        const url = "http://api.alquran.cloud/ayah/" + obj.surah + ":" + obj.localVerse + "/editions/ar." + this.options.explainer;
        fetch(url)
          .then(res => res.json())
          .then(res => {
            const text = res.data[0].text;
            this.$parent.$parent.$parent.modal = {
              name: "explanation",
              data: { text, explainer: this.options.explainer },
            };
          })
          .catch(err => {
            console.error(err);
            this.$parent.$parent.$parent.modal = {
              name: "explanation",
              data: { error: true },
            };
          });
      },
      showNetworkHint() {
        this.$parent.notifyDesc = "انت غير متصل بالانترنت";
        this.$parent.notifyShown = true;
        this.$parent.notifyClass = "alert";
        setTimeout(() => {
          this.$parent.notifyDesc = "";
          this.$parent.notifyShown = false;
        }, 2000);
      },
      isOffline() {
        if (navigator) {
          if (cordova) {
            if (navigator.connection && navigator.connection.type) {
              if (navigator.connection.type === "none") return true;
              else return false;
            } else {
              return true;
            }
          } else {
            return navigator.onLine;
          }
        }
        return true;
      },
      getVerseTrans(obj) {
        if (this.isOffline()) return this.showNetworkHint();
        const url = "http://api.alquran.cloud/v1/ayah/" + obj.surah + ":" + obj.localVerse + "/en." + this.options.translator;
        fetch(url)
          .then(res => res.json())
          .then(res => {
            const text = res.data.text;
            this.$parent.$parent.$parent.modal = {
              name: "trans",
              data: { text, translator: this.options.translator },
            };
          })
          .catch(err => {
            console.error(err);
            this.$parent.$parent.$parent.modal = {
              name: "trans",
              data: { error: true },
            };
          });
      },
      copyText(obj) {
        const text = this.$filters.normalize(obj.text);
        console.log(text);
        if (cordova && cordova.plugins && cordova.plugins.clipboard && cordova.plugins.clipboard.copy) {
          cordova.plugins.clipboard.copy(text);
        } else {
          navigator.clipboard.writeText(text);
        }
        this.$emit("textCopied");
      },
      highlight(obj, e) {
        let color = null;
        if (e.target.classList.contains("orange")) {
          color = "orange";
        } else if (e.target.classList.contains("purple")) {
          color = "purple";
        } else if (e.target.classList.contains("blue")) {
          color = "blue";
        } else if (e.target.classList.contains("noColor")) {
          color = "noColor";
        }

        // reset classes
        this.options.coords.elm.classList.remove("selected", "orange", "blue", "purple", "noColor");
        // add current selected color
        this.options.coords.elm.classList.add(color);
        obj.color = color; // bind color

        let highlightedVersesArr = JSON.parse(localStorage.getItem("highlightedVerses")) || [];

        if (color === "noColor") {
          console.warn("noColor");
          highlightedVersesArr = highlightedVersesArr.filter(item => item.globalVerse !== obj.globalVerse);
          // update storage
          localStorage.setItem("highlightedVerses", JSON.stringify(highlightedVersesArr));
          return;
        }

        // handle new verse
        const status = highlightedVersesArr.find(item => {
          if (item.globalVerse === obj.globalVerse) {
            item.color = color;
            return true;
          }
          return null;
        });
        if (!status) highlightedVersesArr.push(obj);

        // update storage
        localStorage.setItem("highlightedVerses", JSON.stringify(highlightedVersesArr));
        console.log(highlightedVersesArr);
      },
    },
  };
</script>

<style lang="scss">
  .OptionsRect {
    position: fixed;
    top: 0;
    margin: 0 auto;
    padding: 0 5px;
    display: flex;
    flex-direction: row-reverse;
    width: fit-content;
    background: white;
    color: white;
    border-radius: 3px;
    font-weight: bold;
    font-family: "Tajawal", Helvetica, Arial, sans-serif;
    z-index: 999;
    user-select: none;
    box-shadow: 1px 1px 3px 1px rgba(0, 0, 0, 0.1), -1px -1px 3px 1px rgba(0, 0, 0, 0.1);
    > div {
      display: inline-block;
    }
    button {
      width: 20px;
      height: 20px;
      border-radius: 5px;
      border: 0;
      outline: 0;
      margin: 0;
      background: white;
      padding: 5px;
      position: relative;
      cursor: pointer;
      box-sizing: content-box;
      display: block;
      svg {
        position: absolute;
        pointer-events: none;
        width: 20px;
        height: 20px;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: #8c8c8c;
      }
      &:hover {
        svg {
          color: #2f70ec;
          transition: fill 0.3s ease;
          transform: translate(-50%, -50%);
        }
      }

      &:active {
        transform: perspective(1px) translateZ(-0.04px);
        transition: 200ms cubic-bezier(0.12, 0.8, 0.32, 1);
      }
    }

    .highlight {
      position: relative;
      padding-right: 5px;
      margin-right: 5px;
      button {
        border-radius: 50%;
        float: right;
        box-sizing: border-box;
        margin: 5px 5px 0 0;
        &.orange {
          background: #ff8214;
        }
        &.purple {
          background: #8b0efe;
        }
        &.blue {
          background: #0671ff;
        }
        &.noColor {
          background: white;
          border: 1px solid #ccc;
          position: relative;
          &::after {
            position: absolute;
            content: "";
            width: 2px;
            height: 100%;
            background: #f94c66;
            left: 50%;
            top: 50%;
            transform: rotate(45deg) translate(-50%, -50%);
            transform-origin: top left;
          }
        }
      }

      &::after {
        position: absolute;
        content: "";
        right: 0;
        top: 50%;
        width: 1px;
        height: calc(100% - 15px);
        background: #e2e2e2;
        transform: translateY(-50%);
      }
    }

    .trans {
    }
    .copyText {
    }
    .explain {
    }
    .sound {
    }
  }
</style>

// components/modals/OptionsRect.jsx
'use client';
import { useRef, useLayoutEffect, useState } from 'react';
import { useApp } from '../../context/AppContext';
import icons from '../../services/icons';
import { normalize } from '../../services/filters';

export default function OptionsRect({ options, onUpdate, onTextCopied, onClose, isAuto, onPlayVerse }) {
  const { setModal, audioRef, readViewRef } = useApp();
  const rectRef = useRef(null);
  const [style, setStyle] = useState({ visibility: 'hidden', top: '0px', left: '0px', position: 'fixed' });

  const isAutoRef = useRef(isAuto);
  isAutoRef.current = isAuto;

  const reciteVerseRef = useRef(null);

  useLayoutEffect(() => {
    if (!rectRef.current) return;
    const { width, height } = rectRef.current.getBoundingClientRect();
    const { top, left, right, width: coordWidth } = options.coords;
    const newTop = top - height - 5;
    const newLeft = coordWidth < width ? right - width : left;
    setStyle({ position: 'fixed', visibility: 'visible', top: newTop + 'px', left: newLeft + 'px' });
  }, [options.coords]);

  const isOffline = () => typeof navigator !== 'undefined' ? !navigator.onLine : true;

  const showNetworkHint = () => {
    if (onUpdate) onUpdate({ networkHint: true, notifyDesc: 'انت غير متصل بالانترنت', notifyClass: 'alert' });
  };

  const deselectVerses = () => {
    document.querySelectorAll('.page .verse').forEach(el => el.classList.remove('selected'));
  };

  const reciteVerse = (obj) => {
    if (isOffline()) return showNetworkHint();
    const audio = audioRef.current;
    if (!audio) return;

    obj = window.verses[obj.globalVerse - 1];
    if (!obj) return;

    if (isAutoRef.current && readViewRef.current && obj.page) {
      readViewRef.current.setPage(obj.page);
    }

    if (!audio.paused) {
      audio.pause();
      if (onUpdate) onUpdate({ isPlaying: false, isInitialPlaying: true });
    }
    audio.src = '';
    deselectVerses();

    const globalVerse = obj.globalVerse;
    audio.src = `https://cdn.islamic.network/quran/audio/64/ar.${options.reciter}/${globalVerse}.mp3`;

    audio.onended = () => {
      if (onUpdate) onUpdate({ isPlaying: false, isInitialPlaying: true });
      deselectVerses();
      if (isAutoRef.current && globalVerse < 6236) {
        reciteVerseRef.current?.({ globalVerse: globalVerse + 1 });
      }
    };

    audio.play().catch(() => {});
    if (onUpdate) onUpdate({ isPlaying: true, isInitialPlaying: true });

    if (onPlayVerse) onPlayVerse(globalVerse);
  };

  reciteVerseRef.current = reciteVerse;

  const getVerseExplanation = (obj) => {
    if (isOffline()) return showNetworkHint();
    const url = `https://api.alquran.cloud/v1/ayah/${obj.surah}:${obj.localVerse}/editions/ar.${options.explainer}`;
    fetch(url)
      .then(r => r.json())
      .then(res => {
        setModal({ name: 'explanation', data: { text: res.data[0].text, explainer: options.explainer } });
      })
      .catch(() => setModal({ name: 'explanation', data: { error: true } }));
  };

  const getVerseTrans = (obj) => {
    if (isOffline()) return showNetworkHint();
    const url = `https://api.alquran.cloud/v1/ayah/${obj.surah}:${obj.localVerse}/en.${options.translator}`;
    fetch(url)
      .then(r => r.json())
      .then(res => {
        setModal({ name: 'trans', data: { text: res.data.text, translator: options.translator } });
      })
      .catch(() => setModal({ name: 'trans', data: { error: true } }));
  };

  const copyText = (obj) => {
    const text = normalize(obj.text);
    navigator.clipboard.writeText(text).catch(() => {});
    if (onTextCopied) onTextCopied();
  };

  const highlightVerse = (obj, e) => {
    const classList = e.target.classList;
    let color = null;
    if (classList.contains('orange')) color = 'orange';
    else if (classList.contains('purple')) color = 'purple';
    else if (classList.contains('blue')) color = 'blue';
    else if (classList.contains('noColor')) color = 'noColor';
    if (!color) return;

    const elm = options.coords.elm;
    if (!elm) return;
    elm.classList.remove('selected', 'orange', 'blue', 'purple', 'noColor', 'red');

    let arr = JSON.parse(localStorage.getItem('highlightedVerses')) || [];

    if (color === 'noColor') {
      arr = arr.filter(item => item.globalVerse !== obj.globalVerse);
      localStorage.setItem('highlightedVerses', JSON.stringify(arr));
      if (onClose) onClose();
      return;
    }

    elm.classList.add(color);
    obj.color = color;

    const existing = arr.find(item => item.globalVerse === obj.globalVerse);
    if (existing) {
      existing.color = color;
    } else {
      arr.push(obj);
    }
    localStorage.setItem('highlightedVerses', JSON.stringify(arr));
    if (onClose) onClose();
  };

  if (!options.obj) return null;

  return (
    <div
      className="OptionsRect fixed top-0 m-auto px-[5px] flex flex-row-reverse w-fit bg-white text-white rounded-[3px] font-bold font-tajawal z-[999] select-none shadow-[1px_1px_3px_1px_rgba(0,0,0,0.1),-1px_-1px_3px_1px_rgba(0,0,0,0.1)]"
      ref={rectRef}
      style={style}
    >
      <div
        className="inline-block relative pr-[5px] mr-[5px] after:absolute after:content-[''] after:right-0 after:top-1/2 after:-translate-y-1/2 after:w-px after:h-[calc(100%-15px)] after:bg-[#e2e2e2]"
        onClick={(e) => highlightVerse(options.obj, e)}
      >
        <button className="orange rounded-full float-right box-border m-[5px_5px_0_0] w-[20px] h-[20px] border-0 outline-0 cursor-pointer bg-[#ff8214] p-[5px]" />
        <button className="purple rounded-full float-right box-border m-[5px_5px_0_0] w-[20px] h-[20px] border-0 outline-0 cursor-pointer bg-[#8b0efe] p-[5px]" />
        <button className="blue rounded-full float-right box-border m-[5px_5px_0_0] w-[20px] h-[20px] border-0 outline-0 cursor-pointer bg-[#0671ff] p-[5px]" />
        <button className="noColor rounded-full float-right box-border m-[5px_5px_0_0] w-[20px] h-[20px] border border-[#ccc] cursor-pointer bg-white p-[5px] relative after:absolute after:content-[''] after:w-[2px] after:h-full after:bg-[#f94c66] after:left-1/2 after:top-1/2 after:rotate-45 after:-translate-x-1/2 after:-translate-y-1/2 after:origin-top-left" />
      </div>
      <div className="inline-block">
        <button
          className="opts-rect-btn w-[20px] h-[20px] border-0 outline-0 m-0 bg-white p-[5px] cursor-pointer box-content block active:[transform:perspective(1px)_translateZ(-0.04px)] active:transition-[200ms_cubic-bezier(0.12,0.8,0.32,1)]"
          onClick={() => getVerseTrans(options.obj)}
          dangerouslySetInnerHTML={{ __html: icons.translate }}
        />
      </div>
      <div className="inline-block">
        <button
          className="opts-rect-btn w-[20px] h-[20px] border-0 outline-0 m-0 bg-white p-[5px] cursor-pointer box-content block active:[transform:perspective(1px)_translateZ(-0.04px)] active:transition-[200ms_cubic-bezier(0.12,0.8,0.32,1)]"
          onClick={() => copyText(options.obj)}
          dangerouslySetInnerHTML={{ __html: icons.clipboard }}
        />
      </div>
      <div className="inline-block">
        <button
          className="opts-rect-btn w-[20px] h-[20px] border-0 outline-0 m-0 bg-white p-[5px] cursor-pointer box-content block active:[transform:perspective(1px)_translateZ(-0.04px)] active:transition-[200ms_cubic-bezier(0.12,0.8,0.32,1)]"
          onClick={() => getVerseExplanation(options.obj)}
          dangerouslySetInnerHTML={{ __html: icons.book }}
        />
      </div>
      <div className="inline-block">
        <button
          className="opts-rect-btn w-[20px] h-[20px] border-0 outline-0 m-0 bg-white p-[5px] cursor-pointer box-content block active:[transform:perspective(1px)_translateZ(-0.04px)] active:transition-[200ms_cubic-bezier(0.12,0.8,0.32,1)]"
          onClick={() => reciteVerse(options.obj)}
          dangerouslySetInnerHTML={{ __html: icons.play }}
        />
      </div>
    </div>
  );
}
